// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Habit struct {
	ID               int64
	UserID           int64
	Name             string
	WeeklyGoal       int32
	RewardPerExecute int32
	CreatedAt        pgtype.Timestamptz
}

type HabitLog struct {
	ID         int64
	HabitID    int64
	ExecutedAt pgtype.Timestamptz
}

type Project struct {
	ID     int64
	UserID int64
	Name   string
}

type Purchase struct {
	ID          int64
	UserID      int64
	ShopItemID  pgtype.Int8
	PricePaid   int32
	PurchasedAt pgtype.Timestamptz
}

type ShopItem struct {
	ID          int64
	UserID      int64
	Name        string
	Price       int32
	IsPurchased bool
}

type Task struct {
	ID            int64
	UserID        int64
	ProjectID     pgtype.Int8
	Title         string
	ScheduledDate pgtype.Date
	RewardValue   int32
	Status        string
	CompletedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID         int64
	UserID     int64
	Amount     int32
	Source     string
	SourceName string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID                int64
	Timezone          pgtype.Text
	Balance           pgtype.Int4
	RewardWeeklyBonus int32
	CreatedAt         pgtype.Timestamptz
}

type WeeklyBonuse struct {
	ID        int64
	UserID    int64
	WeekStart pgtype.Date
	ClaimedAt pgtype.Timestamptz
}
