// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (user_id, name, weekly_goal, reward_per_execute)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, weekly_goal, reward_per_execute, created_at
`

type CreateHabitParams struct {
	UserID           int64
	Name             string
	WeeklyGoal       int32
	RewardPerExecute int32
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.UserID,
		arg.Name,
		arg.WeeklyGoal,
		arg.RewardPerExecute,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.WeeklyGoal,
		&i.RewardPerExecute,
		&i.CreatedAt,
	)
	return i, err
}

const createHabitLog = `-- name: CreateHabitLog :one
INSERT INTO habit_logs (habit_id, executed_at)
VALUES ($1, NOW())
RETURNING id, habit_id, executed_at
`

func (q *Queries) CreateHabitLog(ctx context.Context, habitID int64) (HabitLog, error) {
	row := q.db.QueryRow(ctx, createHabitLog, habitID)
	var i HabitLog
	err := row.Scan(&i.ID, &i.HabitID, &i.ExecutedAt)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name
`

type CreateProjectParams struct {
	ID     int64
	UserID int64
	Name   string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.UserID, arg.Name)
	var i Project
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (user_id, shop_item_id, price_paid)
VALUES ($1, $2, $3)
RETURNING id, user_id, shop_item_id, price_paid, purchased_at
`

type CreatePurchaseParams struct {
	UserID     int64
	ShopItemID pgtype.Int8
	PricePaid  int32
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, createPurchase, arg.UserID, arg.ShopItemID, arg.PricePaid)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ShopItemID,
		&i.PricePaid,
		&i.PurchasedAt,
	)
	return i, err
}

const createShopItem = `-- name: CreateShopItem :one
INSERT INTO shop_items (user_id, name, price)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, price, is_purchased
`

type CreateShopItemParams struct {
	UserID int64
	Name   string
	Price  int32
}

func (q *Queries) CreateShopItem(ctx context.Context, arg CreateShopItemParams) (ShopItem, error) {
	row := q.db.QueryRow(ctx, createShopItem, arg.UserID, arg.Name, arg.Price)
	var i ShopItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Price,
		&i.IsPurchased,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, amount, source, source_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, amount, source, source_id, created_at
`

type CreateTransactionParams struct {
	UserID   int64
	Amount   int32
	Source   string
	SourceID pgtype.Int8
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Source,
		arg.SourceID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Source,
		&i.SourceID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, timezone, reward_weekly_bonus)
VALUES ($1, $2, $3)
RETURNING id, timezone, balance, reward_weekly_bonus, created_at
`

type CreateUserParams struct {
	ID                int64
	Timezone          pgtype.Text
	RewardWeeklyBonus int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Timezone, arg.RewardWeeklyBonus)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Timezone,
		&i.Balance,
		&i.RewardWeeklyBonus,
		&i.CreatedAt,
	)
	return i, err
}

const createWeeklyBonus = `-- name: CreateWeeklyBonus :exec
INSERT INTO weekly_bonuses (user_id, week_start)
VALUES ($1, $2)
`

type CreateWeeklyBonusParams struct {
	UserID    int64
	WeekStart pgtype.Date
}

func (q *Queries) CreateWeeklyBonus(ctx context.Context, arg CreateWeeklyBonusParams) error {
	_, err := q.db.Exec(ctx, createWeeklyBonus, arg.UserID, arg.WeekStart)
	return err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits
WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteHabit, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteShopItem = `-- name: DeleteShopItem :exec
DELETE FROM shop_items
WHERE id = $1 AND is_purchased = false
`

func (q *Queries) DeleteShopItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteShopItem, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, timezone
FROM users
`

type GetAllUsersRow struct {
	ID       int64
	Timezone pgtype.Text
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.ID, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalanceByUserID = `-- name: GetBalanceByUserID :one
SELECT balance
FROM users
WHERE id = $1
`

func (q *Queries) GetBalanceByUserID(ctx context.Context, id int64) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getBalanceByUserID, id)
	var balance pgtype.Int4
	err := row.Scan(&balance)
	return balance, err
}

const habitByID = `-- name: HabitByID :one
SELECT id, user_id, name, weekly_goal, reward_per_execute, created_at
FROM habits
WHERE id = $1
LIMIT 1
`

func (q *Queries) HabitByID(ctx context.Context, id int64) (Habit, error) {
	row := q.db.QueryRow(ctx, habitByID, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.WeeklyGoal,
		&i.RewardPerExecute,
		&i.CreatedAt,
	)
	return i, err
}

const habitLogsByHabitID = `-- name: HabitLogsByHabitID :many
SELECT id, habit_id, executed_at
FROM habit_logs
WHERE habit_id = $1
ORDER BY executed_at DESC
`

func (q *Queries) HabitLogsByHabitID(ctx context.Context, habitID int64) ([]HabitLog, error) {
	rows, err := q.db.Query(ctx, habitLogsByHabitID, habitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HabitLog
	for rows.Next() {
		var i HabitLog
		if err := rows.Scan(&i.ID, &i.HabitID, &i.ExecutedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const habitLogsForWeek = `-- name: HabitLogsForWeek :many
SELECT id, habit_id, executed_at
FROM habit_logs
WHERE habit_id = $1
  AND executed_at >= $2   -- week_start (timestamp with time zone)
  AND executed_at <  $2 + INTERVAL '7 days'
ORDER BY executed_at
`

type HabitLogsForWeekParams struct {
	HabitID    int64
	ExecutedAt pgtype.Timestamptz
}

func (q *Queries) HabitLogsForWeek(ctx context.Context, arg HabitLogsForWeekParams) ([]HabitLog, error) {
	rows, err := q.db.Query(ctx, habitLogsForWeek, arg.HabitID, arg.ExecutedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HabitLog
	for rows.Next() {
		var i HabitLog
		if err := rows.Scan(&i.ID, &i.HabitID, &i.ExecutedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const habitsByUserID = `-- name: HabitsByUserID :many
SELECT id, user_id, name, weekly_goal, reward_per_execute, created_at
FROM habits
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) HabitsByUserID(ctx context.Context, userID int64) ([]Habit, error) {
	rows, err := q.db.Query(ctx, habitsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.WeeklyGoal,
			&i.RewardPerExecute,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markShopItemPurchased = `-- name: MarkShopItemPurchased :exec
UPDATE shop_items
SET is_purchased = true
WHERE id = $1
`

func (q *Queries) MarkShopItemPurchased(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markShopItemPurchased, id)
	return err
}

const projectByID = `-- name: ProjectByID :one
SELECT id, user_id, name
FROM projects
WHERE id = $1
LIMIT 1
`

func (q *Queries) ProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, projectByID, id)
	var i Project
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const projectsByUserID = `-- name: ProjectsByUserID :many
SELECT id, user_id, name
FROM projects
WHERE user_id = $1
`

func (q *Queries) ProjectsByUserID(ctx context.Context, userID int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, projectsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purchasesByUserID = `-- name: PurchasesByUserID :many
SELECT id, user_id, shop_item_id, price_paid, purchased_at
FROM purchases
WHERE user_id = $1
ORDER BY purchased_at DESC
`

func (q *Queries) PurchasesByUserID(ctx context.Context, userID int64) ([]Purchase, error) {
	rows, err := q.db.Query(ctx, purchasesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Purchase
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ShopItemID,
			&i.PricePaid,
			&i.PurchasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shopItemByID = `-- name: ShopItemByID :one
SELECT id, user_id, name, price, is_purchased
FROM shop_items
WHERE id = $1
LIMIT 1
`

func (q *Queries) ShopItemByID(ctx context.Context, id int64) (ShopItem, error) {
	row := q.db.QueryRow(ctx, shopItemByID, id)
	var i ShopItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Price,
		&i.IsPurchased,
	)
	return i, err
}

const shopItemsByUserID = `-- name: ShopItemsByUserID :many
SELECT id, user_id, name, price, is_purchased
FROM shop_items
WHERE user_id = $1 AND is_purchased = $2
`

type ShopItemsByUserIDParams struct {
	UserID      int64
	IsPurchased bool
}

func (q *Queries) ShopItemsByUserID(ctx context.Context, arg ShopItemsByUserIDParams) ([]ShopItem, error) {
	rows, err := q.db.Query(ctx, shopItemsByUserID, arg.UserID, arg.IsPurchased)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopItem
	for rows.Next() {
		var i ShopItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Price,
			&i.IsPurchased,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskByID = `-- name: TaskByID :one
SELECT id, user_id, project_id, title, scheduled_date, reward_value, status, completed_at, created_at
FROM tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) TaskByID(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, taskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.ScheduledDate,
		&i.RewardValue,
		&i.Status,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const tasksByUserAndStatus = `-- name: TasksByUserAndStatus :many
SELECT id, user_id, project_id, title, scheduled_date, reward_value, status, completed_at, created_at
FROM tasks
WHERE user_id = $1 AND status = $2
ORDER BY scheduled_date
`

type TasksByUserAndStatusParams struct {
	UserID int64
	Status string
}

func (q *Queries) TasksByUserAndStatus(ctx context.Context, arg TasksByUserAndStatusParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, tasksByUserAndStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Title,
			&i.ScheduledDate,
			&i.RewardValue,
			&i.Status,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionsByUserID = `-- name: TransactionsByUserID :many
SELECT id, user_id, amount, source, source_id, created_at
FROM transactions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type TransactionsByUserIDParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

func (q *Queries) TransactionsByUserID(ctx context.Context, arg TransactionsByUserIDParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, transactionsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Source,
			&i.SourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
set name     = $2
WHERE id = $1
`

type UpdateProjectParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject, arg.ID, arg.Name)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
set project_id = $2,
    title = $3,
    scheduled_date = $4,
    status = $5,
    completed_at = $6
WHERE id = $1
`

type UpdateTaskParams struct {
	ID            int64
	ProjectID     pgtype.Int8
	Title         string
	ScheduledDate pgtype.Date
	Status        string
	CompletedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.ScheduledDate,
		arg.Status,
		arg.CompletedAt,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
set timezone     = $2,
    balance = $3,
    reward_weekly_bonus  = $4
WHERE id = $1
`

type UpdateUserParams struct {
	ID                int64
	Timezone          pgtype.Text
	Balance           pgtype.Int4
	RewardWeeklyBonus int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Timezone,
		arg.Balance,
		arg.RewardWeeklyBonus,
	)
	return err
}

const userByID = `-- name: UserByID :one
SELECT id, timezone, balance, reward_weekly_bonus, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) UserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Timezone,
		&i.Balance,
		&i.RewardWeeklyBonus,
		&i.CreatedAt,
	)
	return i, err
}

const weeklyBonus = `-- name: WeeklyBonus :one
SELECT id, user_id, week_start, claimed_at
FROM weekly_bonuses
WHERE user_id = $1 AND week_start = $2
LIMIT 1
`

type WeeklyBonusParams struct {
	UserID    int64
	WeekStart pgtype.Date
}

func (q *Queries) WeeklyBonus(ctx context.Context, arg WeeklyBonusParams) (WeeklyBonuse, error) {
	row := q.db.QueryRow(ctx, weeklyBonus, arg.UserID, arg.WeekStart)
	var i WeeklyBonuse
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeekStart,
		&i.ClaimedAt,
	)
	return i, err
}
